### ISSUE TITLE
How do you pick a locale in results?

### ISSUE THREAD

**Issue by eugenesvk** [giovannicoppola/alfred-fakeum#1]
I've set two locales in the config (nice UI for setting that), but then as far as I understand, the locale is randomly chosen on every extra letter in e.g. `fake addr`
Is there a way to maybe set a shortcut or a prefix to always generate something in a predefined locale?

**Comment by giovannicoppola** [comment]
yes, although it allows the selection of multiple locales, one only can be used in the workflow.
